language: go
arch: 
  - amd64
  - ppc64le
go:
  - 1.13
  - 1.14
  - 1.15
env:
  - GO111MODULE=on
  - CGO_ENABLED=0
before_install:
  - go get github.com/mattn/goveralls
script:
  - go test -covermode=count -coverprofile=profile.cov . ./css ./html ./js ./json ./svg ./xml
  - goveralls -coverprofile=profile.cov -service travis-ci
